name = "splitdumb"
main = "src/index.ts"
compatibility_date = "2025-12-15"
account_id = "facf6619808dc039df729531bbb26d1d"

[[routes]]
pattern = "splitdumb.emilycogsdill.com"
custom_domain = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "splitdumb-db"
database_id = "db8b2e02-214a-41d0-9a09-a208ccefaef0"

[dev]
port = 8787
